### ISSUE TITLE
Update to v12.0

### ISSUE THREAD

**Issue by dev-101** [mathiasbynens/unicode-tr51#4]
As stated in the title, v12.0 is now available:
https://www.unicode.org/Public/emoji/12.0/

**Comment by mathiasbynens** [comment]
Fixed, but you should use https://github.com/mathiasbynens/node-unicode-data#readme nowadays.

**Comment by dev-101** [comment]
Thanks, can you please update emoji-regex readme in that case?
https://github.com/mathiasbynens/emoji-regex/blob/master/README.md

**Comment by mathiasbynens** [comment]
Done.
